### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by jlandon** [jlandon/Alexandria#1]
As it stands right now, [Swift Package Manager (SPM)](https://github.com/apple/swift-package-manager) requires all source files to be located in a root Sources/Source/src/srcs directory. This presents a few problems for this repo. The current directory structure groups source files based on functionality (e.g. extensions, utility classes, views, etc.). It _is_ possible to simply nest these directories inside of Sources/, however, importing Alexandria as a whole is then not possible. For example, with a directory hierarchy such as this:

```
Sources/
   - Extensions/
   - Generics/
   - Transformers/
   - Types/
   - Utilities/
   - Views/
```

After building the package (i.e. `swift build`), each subdirectory is created as its own framework, so each one must be imported separately.

``` swift
import Extensions
import Generics
...
```

Additionally, SPM currently has "no support for iOS, watchOS, or tvOS platforms". Since this repo currently only supports iOS projects and includes many extensions/utilities/views depending upon UIKit, there isn't much incentive to include SPM support at this time. When iOS support is inevitably added to SPM, we'll revisit this.

**Comment by hsoi** [comment]
Note that some of the above issues no longer apply (they did back in JunkDrawer, but in anticipation of SPM support we did centralize into `Sources` for Alexandria.

But the latter issue remains our chief blocker.
